version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: itaclimb_dev
      POSTGRES_PASSWORD: itaclimb_dev
      POSTGRES_DB: itaclimb_dev
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/app
      - deps:/app/deps
      - _build:/app/_build
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://itaclimb_dev:itaclimb_dev@db/itaclimb_dev
      - IMGKITPUBKEY=${IMGKITPUBKEY}
      - IMGKITPRIVKEY=${IMGKITPRIVKEY}
    depends_on:
      - db
    
volumes:
  deps:
  _build:
  pgdata:

